import React, { Component } from "react";
import Owner from "../../assets/images/BusinessOwner.jpeg";
import Teams from "../../assets/images/TeamMembers.jpeg";
import Fibonacci from "../../assets/images/Fibonacci.png";
import "../../vibe/scss/components/Keywords.scss";

class Keywords extends Component {
  state = {};
  render() {
    return (
      <div className="sample-body">
        <div className="container">
          <div className="card">
            <div className="imgBx">
              <img src={Fibonacci}></img>
            </div>
            <div class="content">
              <h6>Fibonacci Sequence:</h6>
              <p>
                Fibonacci sequence is a mathematical series of numbers that was
                introduced in the 13th century and used to explain certain
                formative aspects of nature, such as the branching of trees. The
                series is generated by adding the two previous numbers together
                to get the next value in the sequence: 0, 1, 1, 2, 3, 5, 8, 13,
                21, and so on. For agile estimation purposes, some of the
                numbers have been changed, resulting in the following series: 1,
                2, 3, 5, 8, 13, 20, 40, 100.
              </p>
            </div>
          </div>
        </div>
      </div>
    );
  }
}

export default Keywords;
