import React, { Component } from 'react';
import Owner from '../../assets/images/BusinessOwner.jpeg';
import Teams from '../../assets/images/TeamMembers.jpeg';
import Fibonacci from '../../assets/images/Fibonacci.png';
import '../../vibe/scss/components/Keywords.scss';

class Keywords extends Component {
	state = {};
	render() {
		return (
			<div className="sample-body">
				<div className="container">
					<div className="row comp">
						<div className="imgBx1 col-md-4">
							<img src={Fibonacci} />
						</div>
						<div class="content col-md-8">
							<h5>Fibonacci Sequence:</h5>
							<p>
								Fibonacci sequence is a mathematical series of numbers that is generated by adding the
								two previous numbers together to get the next value in the sequence: 0, 1, 1, 2, 3, 5,
								8, 13, 21, and so on. For agile estimation purposes, some of the numbers have been
								changed, resulting in the following series: 1, 2, 3, 5, 8, 13, 20, 40, 100.
							</p>
						</div>
					</div>

					<div className="row comp">
						<div class="content col-md-8">
							<h5>Business Owner:</h5>
							<p>
								A strategic role responsible for representing the interests of the customer for the
								development team.They have the knowledge and authority to make strategic decisions and
								clear the path of political and financial obstacles.
							</p>
						</div>
						<div className="imgBx2 col-md-4">
							<img src={Owner} />
						</div>
					</div>

					<div className="row comp">
						<div className="imgBx1 col-md-4 teams">
							<img src={Teams} />
						</div>
						<div class="content col-md-8">
							<h5>Team Members:</h5>
							<p>
								it consists of people from development, testing, designing teams. These people
								participate in estimation and give their reviews about the project as per their fields.
							</p>
						</div>
					</div>
				</div>
			</div>
		);
	}
}

export default Keywords;
